### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by johnjohndoe** [Larpon/RangeSeekBar#4]
Since you released version 1.0 recently I like to point you to the topic of [sematic versioning](http://semver.org). Please consider following after this common pattern whenever you pusblish a new version of your library.

**Comment by Larpon** [comment]
Version 1.0.1 is out following the semantics!
Hopefully nothing is too broken (although the /res/values/attrs.xml have changed and may/will break 1.0 compatibility - I don't know how I could have prevented this - it wouldn't build otherwise? - suggestions/fixes are welcome)

**Comment by johnjohndoe** [comment]
Nobody stops you from using v.1.1.0 if you think the changes are breaking.

**Comment by Larpon** [comment]
:+1: I'm still learning :)
